# Generated by Django 4.2.4 on 2023-08-09 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='deportista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='tareas/images')),
                ('ceduladeportista', models.TextField(max_length=10, unique=True)),
                ('tipodeportista', models.TextField(choices=[('MASTER', 'Master'), ('EVENTUAL', 'Eventual')], default='EVENTUAL', max_length=8)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1)),
                ('tiposangre', models.TextField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3)),
                ('apellidosdeportista', models.TextField(max_length=100)),
                ('nombresdeportista', models.TextField(max_length=100)),
                ('fecnacdeportista', models.DateField(default='1990-01-01', null=True)),
                ('email', models.EmailField(blank=True, default='sincorreo@sincorreo.com', max_length=254)),
                ('direcciondeportista', models.TextField(blank=True, max_length=200)),
                ('telefonofijo', models.TextField(blank=True, max_length=20)),
                ('telefonomovil', models.TextField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='eventodeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechainicioevento', models.DateField(null=True)),
                ('fechafinevento', models.DateField(null=True)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='imagenesaplicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tareas/images')),
            ],
        ),
        migrations.CreateModel(
            name='parametroevaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionparametro', models.TextField(max_length=100)),
                ('ponderacionminima', models.TextField(max_length=4)),
                ('ponderacionmaxima', models.TextField(max_length=4)),
                ('unidadmedida', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='representante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedularepresentante', models.TextField(max_length=10, unique=True)),
                ('apellidosrepresentante', models.TextField(max_length=100)),
                ('nombresrepresentante', models.TextField(max_length=100)),
                ('telefonofijo', models.TextField(blank=True, max_length=20)),
                ('telefonomovil', models.TextField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, default='sincorreo@sincorreo.com', max_length=254)),
                ('direccionrepresentante', models.TextField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='historicorepresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodorepresentacion', models.TextField(max_length=100)),
                ('observacion', models.TextField(max_length=100)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.deportista')),
                ('representante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.representante')),
            ],
        ),
        migrations.CreateModel(
            name='evaluacionpreviacompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(max_length=4)),
                ('observacion', models.TextField(max_length=100)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.deportista')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.eventodeportivo')),
            ],
        ),
        migrations.CreateModel(
            name='estadoinicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(max_length=4)),
                ('observacion', models.TextField(max_length=100)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.deportista')),
                ('parametroevaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.parametroevaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tareas.deportista')),
            ],
        ),
    ]
