# Generated by Django 4.2.4 on 2023-08-09 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='rendimientocompetencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.TextField(max_length=4)),
                ('observacion', models.TextField(max_length=100)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.deportista')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.eventodeportivo')),
            ],
        ),
        migrations.AlterField(
            model_name='estadoinicial',
            name='deportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.deportista'),
        ),
        migrations.AlterField(
            model_name='estadoinicial',
            name='parametroevaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.parametroevaluacion'),
        ),
        migrations.AlterField(
            model_name='historicorepresentacion',
            name='deportista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.deportista'),
        ),
        migrations.AlterField(
            model_name='historicorepresentacion',
            name='representante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.representante'),
        ),
        migrations.DeleteModel(
            name='evaluacionpreviacompetencia',
        ),
    ]
