# Generated by Django 4.2.4 on 2023-08-10 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0004_eventodeportivo_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacionestadofisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('valor', models.FloatField()),
                ('observacion', models.TextField(max_length=200)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.deportista')),
            ],
        ),
        migrations.CreateModel(
            name='fechascontrol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='rendimientoinscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('posicion', models.TextField(max_length=20)),
                ('tiempominutos', models.IntegerField()),
                ('tiemposegundos', models.IntegerField()),
                ('tipoestilo', models.TextField(choices=[('PECHO', 'PECHO'), ('MARIPOSA', 'MARIPOSA'), ('ESPALDA', 'ESPALDA'), ('LIBRE', 'LIBRE'), ('AGUAS_ABIERTAS', 'AGUAS_ABIERTAS'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=15)),
                ('observacion', models.TextField(max_length=100)),
                ('deportista', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.deportista')),
            ],
        ),
        migrations.RemoveField(
            model_name='rendimientocompetencia',
            name='deportista',
        ),
        migrations.RemoveField(
            model_name='rendimientocompetencia',
            name='evento',
        ),
        migrations.RenameField(
            model_name='asistencia',
            old_name='valor',
            new_name='controlasiste',
        ),
        migrations.RemoveField(
            model_name='asistencia',
            name='fecha',
        ),
        migrations.AddField(
            model_name='asistencia',
            name='observacion',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='eventodeportivo',
            name='tipoevento',
            field=models.TextField(choices=[('COMPETENCIA', 'COMPETENCIA'), ('CURSO', 'CURSO'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionmaxima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionminima',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='unidadmedida',
            field=models.TextField(max_length=40),
        ),
        migrations.DeleteModel(
            name='estadoinicial',
        ),
        migrations.DeleteModel(
            name='rendimientocompetencia',
        ),
        migrations.AddField(
            model_name='rendimientoinscripcion',
            name='evento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.eventodeportivo'),
        ),
        migrations.AddField(
            model_name='evaluacionestadofisico',
            name='parametroevaluacion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.parametroevaluacion'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='fechacontrol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tareas.fechascontrol'),
        ),
    ]
