# Generated by Django 4.2.4 on 2023-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0005_evaluacionestadofisico_fechascontrol_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='posicion',
            field=models.TextField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiempominutos',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiemposegundos',
            field=models.FloatField(blank=True),
        ),
    ]
