# Generated by Django 4.2.4 on 2023-08-12 07:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0007_alter_rendimientoinscripcion_tiempominutos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventodeportivo',
            name='clave',
            field=models.TextField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventodeportivo',
            name='usuario',
            field=models.TextField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
