# Generated by Django 4.2.4 on 2023-08-12 07:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0008_eventodeportivo_clave_eventodeportivo_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventodeportivo',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='eventodeportivo',
            name='usuario',
        ),
        migrations.AddField(
            model_name='deportista',
            name='clave',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deportista',
            name='usuario',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deportista',
            name='apellidosdeportista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='ceduladeportista',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='nombresdeportista',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='telefonomovil',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tipodeportista',
            field=models.CharField(choices=[('MASTER', 'Master'), ('EVENTUAL', 'Eventual')], default='EVENTUAL', max_length=8),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tiposangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='tipoevento',
            field=models.CharField(choices=[('COMPETENCIA', 'COMPETENCIA'), ('CURSO', 'CURSO'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=12),
        ),
        migrations.AlterField(
            model_name='historicorepresentacion',
            name='periodorepresentacion',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='descripcionparametro',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='unidadmedida',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='posicion',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tipoestilo',
            field=models.CharField(choices=[('PECHO', 'PECHO'), ('MARIPOSA', 'MARIPOSA'), ('ESPALDA', 'ESPALDA'), ('LIBRE', 'LIBRE'), ('AGUAS_ABIERTAS', 'AGUAS_ABIERTAS'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=15),
        ),
        migrations.AlterField(
            model_name='representante',
            name='apellidosrepresentante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedularepresentante',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombresrepresentante',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefonomovil',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
