# Generated by Django 4.2.4 on 2023-08-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0009_remove_eventodeportivo_clave_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='imagenesaplicacion',
        ),
        migrations.AlterField(
            model_name='deportista',
            name='apellidosdeportista',
            field=models.CharField(max_length=100, verbose_name='Apellidos: '),
        ),
        migrations.AlterField(
            model_name='evaluacionestadofisico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionmaxima',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionminima',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiempominutos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiemposegundos',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
