# Generated by Django 4.2.4 on 2023-08-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0010_delete_imagenesaplicacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='apellidosdeportista',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
    ]
