# Generated by Django 4.2.4 on 2023-08-12 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0011_alter_deportista_apellidosdeportista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='controlasiste',
            field=models.BooleanField(default=True, verbose_name='Asistencia/inasistencia'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='observacion',
            field=models.TextField(blank=True, max_length=100, verbose_name='Observación/Justificación'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='ceduladeportista',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='clave',
            field=models.CharField(max_length=100, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='direcciondeportista',
            field=models.TextField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='email',
            field=models.EmailField(blank=True, default='sincorreo@sincorreo.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='fecnacdeportista',
            field=models.DateField(default='1990-01-01', null=True, verbose_name='Fecha de nacimiento'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='nombresdeportista',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='telefonomovil',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono movil'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tipodeportista',
            field=models.CharField(choices=[('MASTER', 'Master'), ('EVENTUAL', 'Eventual')], default='EVENTUAL', max_length=8, verbose_name='Tipo de deportista'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='tiposangre',
            field=models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], default='O+', max_length=3, verbose_name='Tpo de sangre'),
        ),
        migrations.AlterField(
            model_name='deportista',
            name='usuario',
            field=models.CharField(max_length=100, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='evaluacionestadofisico',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evaluacionestadofisico',
            name='observacion',
            field=models.TextField(max_length=200, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='evaluacionestadofisico',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='descripcion',
            field=models.CharField(max_length=100, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Activo/Inactivo'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='fechafinevento',
            field=models.DateField(null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='fechainicioevento',
            field=models.DateField(null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='eventodeportivo',
            name='tipoevento',
            field=models.CharField(choices=[('COMPETENCIA', 'COMPETENCIA'), ('CURSO', 'CURSO'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=12, verbose_name='Tipo de evento'),
        ),
        migrations.AlterField(
            model_name='fechascontrol',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='historicorepresentacion',
            name='observacion',
            field=models.TextField(max_length=100, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='historicorepresentacion',
            name='periodorepresentacion',
            field=models.CharField(max_length=100, verbose_name='Período de representación'),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='descripcionparametro',
            field=models.CharField(max_length=100, verbose_name='Descripción del parámetro'),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionmaxima',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Máximo normal'),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='ponderacionminima',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Mínimo normal'),
        ),
        migrations.AlterField(
            model_name='parametroevaluacion',
            name='unidadmedida',
            field=models.CharField(max_length=20, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='observacion',
            field=models.TextField(max_length=100, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='posicion',
            field=models.CharField(blank=True, max_length=20, verbose_name='Posición'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiempominutos',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Minutos para llegar'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tiemposegundos',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Segundos para llegar'),
        ),
        migrations.AlterField(
            model_name='rendimientoinscripcion',
            name='tipoestilo',
            field=models.CharField(choices=[('PECHO', 'PECHO'), ('MARIPOSA', 'MARIPOSA'), ('ESPALDA', 'ESPALDA'), ('LIBRE', 'LIBRE'), ('AGUAS_ABIERTAS', 'AGUAS_ABIERTAS'), ('VACACIONAL', 'VACACIONAL')], default='VACACIONAL', max_length=15, verbose_name='Estilo evaluado'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='apellidosrepresentante',
            field=models.CharField(max_length=100, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='cedularepresentante',
            field=models.CharField(max_length=10, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='direccionrepresentante',
            field=models.TextField(blank=True, max_length=200, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='email',
            field=models.EmailField(blank=True, default='sincorreo@sincorreo.com', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='nombresrepresentante',
            field=models.CharField(max_length=100, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefonofijo',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono fijo'),
        ),
        migrations.AlterField(
            model_name='representante',
            name='telefonomovil',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono móvil'),
        ),
    ]
