# Generated by Django 4.2.4 on 2023-08-15 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tareas', '0020_alter_deportista_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='clave',
            field=models.CharField(max_length=100, unique=True, verbose_name='Contraseña'),
        ),
    ]
